# Site settings
title: Ugenteraan Manogaran
email: m.ugenteraan15@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "A portfolio about my works thus far. I'm skilled in machine learning & deep learning. Have done a number of freelance projects in the past."
keywords: "machine-learning, deep-learning, devops, mlops"
skills: "Machine Learning - Deep Learning - DevOps - MLOps"
meta_author: Manogaran Ugenteraan

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: ugen

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: D2EEF6 #80B3FF
  primary-rgb: "181,77,8" #"128,179,255"
  secondary: 491f03 #FD6E8A
  secondary-dark: 2b4903 #A2122F

# Footer settings
footer:
  copyright: Ugenteraan Manogaran
  location: Malaysia
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: telegram
    url: https://t.me/Ugenteraan
  - title: linkedin
    url: https://www.linkedin.com/in/ugenteraan/
  - title: github
    url: https://github.com/Ugenteraan

# Postal address (add as many lines as necessary)
address:
  - line: Cyberjaya, Selangor

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
